.PHONY: run1 run2 run3 run4 run5


run1:
python3 src/exercise1/task1.py


run2:
python3 src/exercise2/task2.py


run3:
python3 src/exercise3/task3.py


run4:
python3 src/exercise4/task4.py


run5:
python3 src/exercise5/task5.py
